# Imperial/US units
inch: 0.0254
foot: 0.3048
yard: 0.9144
mile: 1609.344

# Metric units
meter: 1.0
millimeter: 0.001
centimeter: 0.01
decimeter: 0.1
kilometer: 1000.0
micrometer: 1e-6
nanometer: 1e-9

# Astronomical units
light-year: 9.46073047258080e15

# Scientific units
angstrom: 1.0e-10
micron: 1.0e-6

