cubic decimeter: 1.0
cubic centimeter: 0.001
cubic meter: 1000.0
cubic millimeter: 0.000001
gallon (US): 3.78541
quart (US): 0.946353
pint (US): 0.473176
fluid ounce (US): 0.0295735
cup (US): 0.237
tablespoon: 0.015
teaspoon: 0.005
liter: 1